[toolchain]

[features]
resolution = true
skip-lint = false
seeds = true

[programs.localnet]
rebu_solana = "3BjmHpjppF39NVDJbL4UG7pD6tV75fLHMuh7aZU4f2Qc"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"
