[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
rebu_solana = "BhitfXGo3bXsyF5AXQhvnSM28u2tqUkbGabtFPBdoYJc"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo run tests/rebu_solana.rs"
