import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :rebu_web_api, RebuWebApiWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: RebuWebApi.Finch

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

config :rebu_web_api, RebuWebApi.SolanaApi,
  crate: :solana_api,
  skip_compilation?: true,
  load_from: {:rebu_api_web, "priv/native/libsolana_api.so"}

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
